name: Deploy-Pyapp-to-EB-with-RDS-test
env:
  REGION: "eu-central-1"
  ZIP_PACK: "pyapp.zip"
  S3_BUCKET: "s3://anpod07-rds/"
  APP_NAME: "my-pyapp-mysql"

on:
  push:
    branches:
    - main

jobs:
  my_build:
    runs-on: ubuntu-latest
    steps:
    - name: copy my html on Runner
      uses: actions/checkout@v3
    - name: zip package
      run: |
        cd pyapp/
        zip -r ${{ env.ZIP_PACK }} ./
        mv ./${{ env.ZIP_PACK }} ..
        cd ..
    - name: view results
      run: ls -l
    - name: Install Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install EB CLI using pip
      run: |
        python -m pip install --upgrade pip
        pip install awsebcli --upgrade
        aws --version
        eb --version
