name: my_test_CI
env:
  HNAME: "45.8.249.139"
  
on:
  push:
    branches:
    - main

jobs:
  my_build:
    runs-on: ubuntu-latest
    steps:
    - name: deploy my html
      uses: actions/checkout@v3
    - name: view my html
      run: ls -l
#    - name: ping remote host
#      run: ping -c2 ${{ env.HNAME }}
