name: my_test_CI
env:
  IP_ADDR: "18.194.119.138"
  SSH_USER: "ubuntu"
  
on:
  push:
    branches:
    - main

jobs:
  my_build:
    runs-on: ubuntu-latest
    steps:
    - name: copy my html on Runner
      uses: actions/checkout@v3
    - name: view my html
      run: ls -l
#    - name: ping remote host
#      run: ping -c2 ${{ env.IP_ADDR }}
    - name: establish SSH connection
      run: |
        eval $(ssh-agent -s)
        ssh-add <(echo "${{ secrets.SSH_SECRET_KEY }}")
        ssh-add -l
        curl https://2ip.ua
    - name: deploy my html
      run: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ env.SSH_USER }}@${{ env.IP_ADDR }} "hostname && echo 'Welcome!!!' > welcome.txt"
#      run: scp -o StrictHostKeyChecking=no \
#               -o UserKnownHostsFile=/dev/null \
#               -r ./* ${{ env.SSH_USER }}@${{ env.IP_ADDR }}:/home/ubuntu/
               
